/* Generated By:JavaCC: Do not edit this line. XLExpressionConstants.java */
package at.jku.xlwrap.map.expr.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XLExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MUL = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int PERCENT = 10;
  /** RegularExpression Id. */
  int POW = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int LE = 13;
  /** RegularExpression Id. */
  int GE = 14;
  /** RegularExpression Id. */
  int GT = 15;
  /** RegularExpression Id. */
  int NE = 16;
  /** RegularExpression Id. */
  int EQ1 = 17;
  /** RegularExpression Id. */
  int EQ2 = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int DEC = 25;
  /** RegularExpression Id. */
  int EXPONENT = 26;
  /** RegularExpression Id. */
  int CELLRANGE = 27;
  /** RegularExpression Id. */
  int SUBRANGE = 28;
  /** RegularExpression Id. */
  int SHEET = 29;
  /** RegularExpression Id. */
  int FILEURL = 30;
  /** RegularExpression Id. */
  int FUNCIDENT = 31;
  /** RegularExpression Id. */
  int CONSTIDENT = 32;
  /** RegularExpression Id. */
  int SQ_STRING = 33;
  /** RegularExpression Id. */
  int DQ_STRING = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "<NE>",
    "\"=\"",
    "\"==\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<DEC>",
    "<EXPONENT>",
    "<CELLRANGE>",
    "<SUBRANGE>",
    "<SHEET>",
    "<FILEURL>",
    "<FUNCIDENT>",
    "<CONSTIDENT>",
    "<SQ_STRING>",
    "<DQ_STRING>",
    "\"&\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
